fix: Update CI to use GitHub actions and build for osx, windows, linux
googleapis/python-crc32c pull request #51
Opened 2021-01-12 22:35 UTC by crwilcox

This PR
1) fixes an issue in DLL discovery for 3.8, 3.9 on windows
2) configures github actions for releasing new wheels

2021-01-12 22:40 UTC, andrewsg requested changes

2021-01-12 22:40 UTC, andrewsg commented on src/google_crc32c/__config__.py
> +    # 3.6, 3.7 use path
Duplicate comment with below?

2021-01-12 22:40 UTC, andrewsg commented on tests/conftest.py
>  import unittest
I believe this file can be removed entirely if the mock patch is being removed.

2021-01-12 22:41 UTC, crwilcox commented on tests/conftest.py
>  import unittest
yeah, I can delete it :)

2021-01-12 22:42 UTC, crwilcox commented
Will add separate commits to remove some of the old CI that this replaces

2021-01-12 23:01 UTC, crwilcox commented
This action won't run until merge, I have a followup PR to update the readme a bit for this project. 

![Uploading image.png…]()

2021-01-12 23:40 UTC, andrewsg approved these changes
LGTM, with the caveat that I don't understand the yaml file requirements so if it's hand-crafted I can't review its correctness. Thanks for this work!

2021-01-13 07:10 UTC, crwilcox commented
@andrewsg  I did run these with different triggers on my fork so I expect they work as expected 👍

2021-01-13 07:10 UTC, merged